if(NOT DEFINED INPUTS OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "INPUTS and OUTPUT must be defined")
endif()

set(CONTENT "/* Generated by metal_combine_sources.cmake. */\n")

foreach(INPUT ${INPUTS})
  file(READ "${INPUT}" INPUT_CONTENT)
  string(APPEND CONTENT "\n/* Begin ${INPUT} */\n")
  string(APPEND CONTENT "${INPUT_CONTENT}")
  string(APPEND CONTENT "\n/* End ${INPUT} */\n")
endforeach()

file(WRITE "${OUTPUT}" "${CONTENT}")
